service: yearn

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  customDomain: ${file(./config/serverless/domain.js):${self:custom.currentStage}}
  basePath: ""

provider:
  name: aws
  runtime: nodejs12.x
  profile: ${file(./awsProfile.yml):aws_profile}

functions:
  user-earnings:
    handler: services/user/vault/earnings/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - httpApi:
          path: /user/{id}/vaults/earnings
          method: get

  loanscan-link:
    handler: services/loanscan/link/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - httpApi:
          path: /loanscan/link
          method: get

  loanscan-eth-stable:
    handler: services/loanscan/eth-stable/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - httpApi:
          path: /loanscan/ethstable
          method: get

  loanscan-ycrv:
    handler: services/loanscan/ycrv/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - httpApi:
          path: /loanscan/ycrv
          method: get

  loanscan-crvbtc:
    handler: services/loanscan/crvbtc/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - httpApi:
          path: /loanscan/crvbtc
          method: get

  loanscan-crvbusd:
    handler: services/loanscan/crvbusd/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - httpApi:
          path: /loanscan/crvbusd
          method: get

  get-apy:
    handler: services/apy/get-apy/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - httpApi:
          path: /apy
          method: get

  save-apy:
    handler: services/apy/save-apy/handler.handler
    role: arn:aws:iam::698083237070:role/service-role/fetchTokenIds-role-o9i24lq2
    events:
      - httpApi:
          path: /apy/save
          method: get
